<?php

namespace common\widgets;

use yii\helpers\ArrayHelper;
use yii\web\JsExpression;

class TinyMce extends \dosamigos\tinymce\TinyMce
{

    public function run()
    {
        $this->clientOptions = ArrayHelper::merge([
            'class' => ['tinymce-content-container'],
            'menubar' => false,
            'branding' => false,
            'toolbar' => 'undo redo | fontselect | fontsizeselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist ',
            'content_style' => 'body { font-family:Arial, Helvetica, sans-serif; font-size:12pt; }',
            'setup' => new JsExpression("function(editor) {
                editor.on('focusout', function() {
                  editor.save();
                  $('#{$this->options['id']}').val(editor.getContent());
                });        
            }")
        ], $this->clientOptions);
        parent::run(); // TODO: Change the autogenerated stub
    }

}