<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'activated' => 'aktivirina',
    'deactivated' => 'deaktivirana',
    '{:model} canno\'t be {:action}!' => '{:model} ne može biti {:action}!',
    '{:model} could not be created!' => '{:model} nije mogla biti kreirana!',
    '{:model} successfully created!' => '{:model} uspješno kreirana!',
    '{:model} successfully deleted!' => '{:model} uspješno izbrisana!',
    '{:model} successfully updated!' => '{:model} uspješno ažurirana!',
    '{:model} successfully {:action}!' => '{:model} uspješno {:action}!',
    '{:model} canno\'t be updated!' => '{:model} ne može biti ažurirana!',
];
