<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'activated' => 'aktiviran',
    'deactivated' => 'deaktiviran',
    '{:model} canno\'t be {:action}!' => '{:model} ne može biti {:action}!',
    '{:model} could not be created!' => '{:model} nije mogao biti kreiran!',
    '{:model} successfully created!' => '{:model} uspješno kreiran!',
    '{:model} successfully deleted!' => '{:model} uspješno izbrisan!',
    '{:model} successfully updated!' => '{:model} uspješno ažuriran!',
    '{:model} successfully {:action}!' => '{:model} uspješno {:action}!',
    '{:model} canno\'t be updated!' => '{:model} ne može biti ažuriran!',
];
