<?php

namespace common\models;

use common\components\orm\ActiveRecord;
use common\helpers\BaseHelper;
use Yii;
use yii\behaviors\SluggableBehavior;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "product_category".
 *
 * @property int $id
 * @property int|null $parent_category_id
 * @property int|null $cover_image_id
 * @property string|null $name
 * @property string|null $slug
 * @property string|null $description
 * @property int|null $order
 * @property int|null $is_active
 * @property int|null $created_at
 * @property int|null $created_by
 * @property int|null $updated_at
 * @property int|null $updated_by
 * @property int|null $is_deleted
 *
 * @property Image $coverImage
 * @property ProductCategory $parentCategory
 * @property ProductCategory[] $subCategories
 * @property Product[] $products
 */
class ProductCategory extends ActiveRecord
{
    protected static $_i18nCategories = [
        'bs-BS' => 'app/feminine'
    ];

    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;

    const INDEX_GRID_ID = 'product-category-grid';

    public $coverImageIds;

    public static function tableName()
    {
        return 'product_category';
    }

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['parent_category_id', 'cover_image_id', 'order', 'created_at', 'created_by', 'updated_at', 'updated_by', 'is_deleted'], 'integer'],
            [['description'], 'string'],
            [['name', 'slug'], 'string', 'max' => 255],
            [['parent_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => ProductCategory::className(), 'targetAttribute' => ['parent_category_id' => 'id']],
            [['cover_image_id'], 'exist', 'skipOnError' => true, 'targetClass' => Image::className(), 'targetAttribute' => ['cover_image_id' => 'id']],
            [['coverImageIds'], 'safe'],
            [['is_active'], 'default', 'value' => static::STATUS_ACTIVE],
            ['is_active', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE]],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'parent_category_id' => Yii::t('app', 'Parent Category'),
            'cover_image_id' => Yii::t('app', 'Cover Image ID'),
            'name' => Yii::t('app', 'Name'),
            'slug' => Yii::t('app', 'Slug'),
            'description' => Yii::t('app', 'Description'),
            'order' => Yii::t('app', 'Order'),
            'is_active' => Yii::t('app', 'Is Active'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'is_deleted' => Yii::t('app', 'Is Deleted'),
            'coverImageIds' => Yii::t('app', 'Cover Image'),
        ];
    }

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            [
                'class' => SluggableBehavior::class,
                'attribute' => 'name',
                'slugAttribute' => 'slug',
            ],
        ]);
    }

    public function getPublicName()
    {
        return Yii::t("app", 'Category');
    }

    public function beforeValidate()
    {
        if (!empty($this->coverImageIds)) {
            $coverImageIds = BaseHelper::extractIdsFromDropzoneValue($this->coverImageIds, 1);
            $this->cover_image_id = $coverImageIds[0];
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function fields()
    {
        return [
            'id',
            'name',
            'description',
            'slug',
            'cover_image_id',
            'subCategories' => function () {
                return $this->getSubCategories()->andOnCondition([
                    'is_active' => Product::STATUS_ACTIVE
                ])->orderBy(['order' => SORT_ASC])->all();
            }
        ];
    }

    /**
     * Get all descendant category IDs including the current category
     *
     * @param int $categoryId
     * @return array Array of category IDs
     */
    public static function getDescendantIds(int $categoryId): array
    {
        // Load all categories once
        $allCategories = static::find()
            ->select(['id', 'parent_category_id'])
            ->where(['is_deleted' => 0])
            ->asArray()
            ->all();

        // Build a map of parent_id => [child_ids]
        $childrenMap = [];
        foreach ($allCategories as $category) {
            $parentId = $category['parent_category_id'];
            if (!isset($childrenMap[$parentId])) {
                $childrenMap[$parentId] = [];
            }
            $childrenMap[$parentId][] = $category['id'];
        }

        // Recursively collect descendants using the in-memory map
        $descendants = [$categoryId];
        return array_merge($descendants, static::collectDescendants($categoryId, $childrenMap));
    }

    /**
     * Helper method to recursively collect descendants from the children map
     *
     * @param int $categoryId
     * @param array $childrenMap
     * @return array
     */
    private static function collectDescendants(int $categoryId, array $childrenMap): array
    {
        $result = [];

        if (isset($childrenMap[$categoryId])) {
            foreach ($childrenMap[$categoryId] as $childId) {
                $result[] = $childId;
                // Recursively get descendants of this child
                $result = array_merge($result, static::collectDescendants($childId, $childrenMap));
            }
        }

        return $result;
    }

    /**
     * Gets query for [[CoverImage]].
     *
     * @return ActiveQuery
     */
    public function getCoverImage(): ActiveQuery
    {
        return $this->hasOne(Image::className(), ['id' => 'cover_image_id']);
    }

    /**
     * Gets query for [[ParentCategory]].
     *
     * @return ActiveQuery
     */
    public function getParentCategory()
    {
        return $this->hasOne(ProductCategory::className(), ['id' => 'parent_category_id']);
    }

    /**
     * Gets query for [[ProductCategories]].
     *
     * @return ActiveQuery
     */
    public function getSubCategories()
    {
        return $this->hasMany(ProductCategory::className(), ['parent_category_id' => 'id']);
    }

    /**
     * Gets query for [[Products]].
     *
     * @return ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['category_id' => 'id']);
    }
}
