<?php

namespace common\widgets\grid;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

class GridView extends \yii\grid\GridView
{
    public $tableOptions = ['class' => 'table table-striped table-primary table-body-relative mb-2'];
    public $enableSearch = true;
    public $enableAdd = false;
    public $addButtonOption = [];
    public $collapseToggle;
    public $layout;
    public $title;
    public $pager = [
        'firstPageLabel' => '<i class="fas fa-angle-double-left"></i>',
        'lastPageLabel' => '<i class="fas fa-angle-double-right"></i>',
        'prevPageLabel' => '<i class="fas fa-angle-left"></i>',
        'nextPageLabel' => '<i class="fas fa-angle-right"></i>',
        'maxButtonCount' => 3,
        'pageCssClass' => 'page-item',
        'firstPageCssClass' => 'page-item',
        'lastPageCssClass' => 'page-item',
        'nextPageCssClass' => 'page-item',
        'prevPageCssClass' => 'page-item',
        'options' => [
            'class' => 'pagination justify-content-end',
        ],
        'linkOptions' => ['class' => 'page-link'],
    ];

    public function init()
    {
        if (!$this->layout) {
            $this->layout = $this->render('_grid_layout');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $this->layout = Yii::t('app', $this->layout, [
            'collapsable' => $this->collapseToggle,
            'search' => $this->enableSearch ? $this->render('_search', ['title' => $this->title]) : '',
            'add' => $this->enableAdd ? $this->renderAdd() : ''
        ]);
        parent::run(); // TODO: Change the autogenerated stub
    }

    protected function renderAdd()
    {
        $this->addButtonOption = ArrayHelper::merge([
            'class' => 'btn btn-success btn-modal-control btn-loading',
            'data-size' => 'modal-lg'
        ], $this->addButtonOption);

        $link = ArrayHelper::remove($this->addButtonOption, 'link', false);
        $url = ArrayHelper::remove($this->addButtonOption, 'url', Url::to(['create']));
        $content = ArrayHelper::remove($this->addButtonOption, 'content', Yii::t('app', 'Add New'));

        if ($link) {
            return Html::a($content, $url, $this->addButtonOption);
        }

        $this->addButtonOption['data-href'] = $url;

        return Html::tag('span', $content, $this->addButtonOption);
    }
}